from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse
from django.utils.text import slugify

class Posts(models.Model):
    """ Represents a single post """
    title = models.CharField(max_length=600, unique=True, help_text="Title for your post")
    author = models.ForeignKey(User, on_delete=models.PROTECT, help_text="The user that made this post")
    slug = models.CharField(max_length=600, blank=True, editable=False, 
        help_text="Unique URL path to access this page. Generated by the system")
    content = models.TextField(help_text="Write the content of your post here")
    created = models.DateTimeField(auto_now_add=True, 
        help_text="The date and time this page was created. Automatically generated when the model saves.")
    modified = models.DateTimeField(auto_now=True,
        help_text="The date and time this page was last updated. Automatically generated when the model updates.")

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        """ Returns a fully qualified path for a page """
        path_components = {'slug': self.slug}
        return reverse('blog-details-page', kwargs=path_components)

    def save(self, *args, **kwargs):
        """ Creates a URL safe slug automatically when a new page is created """
        if not self.pk:
            self.slug =  slugify(self.title, allow_unicode=True)

        return super(Posts, self).save(*args, **kwargs)

